### ISSUE TITLE
Signed immediate values are unsigned

### ISSUE THREAD

**Issue by Marlamin** [Seyden/CascStorageLib#1]
Small issue [here](https://github.com/Seyden/CascStorageLib/blob/master/CascStorageLib/WDC2Reader.cs#L143) where signed immediate values are handled wrong. 

Fabi shared this fix via Discord:

```
var signedShift = (1 << (bits - 1));
var finalValue =  (signedShift ^ unpackedValue) - signedShift;
```

Test case: ExpectedStat::ExpansionID of 14 [here](https://bnet.marlam.in/dbc.php?dbc=expectedstat.db2&bc=7cde34b5e9929706fb42650c13fc3460#page=1) should be -2.

**Comment by Marlamin** [comment]
Can probably just use Tom's fix from [here](https://github.com/WoW-Tools/CASCExplorer/commit/dfd54d05173c35a1f028dc1956c44e09b515988a#diff-c565052dd784061e061723d004273560R258).

**Comment by Seyden** [comment]
Fixed
