### ISSUE TITLE
1SLC (classic) support

### ISSUE THREAD

**Issue by Marlamin** [Seyden/CascStorageLib#3]
It seems very similar to WDC2, shouldn't be too difficult. You might even get away with loading it as WDC2.

**Comment by funjoker** [comment]
TBH, i guess it is abandoned already.

**Comment by Marlamin** [comment]
Yeah just use the one from DBCD if you need to. https://github.com/wowdev/DBCD/tree/master/DBFileReaderLib

**Comment by Seyden** [comment]
I'm starting to sort out things internally.. i nearly rewrote the whole structure of the loading.. just need to figure some things out before i release everything
